// Horror Movie Database
// 80+ movies from 30+ countries

const HORROR_MOVIES = [
  // USA
  {id:1,title:"The Shining",year:1980,country:"USA",language:"English",genre:"Psychological",rating:8.4,director:"Stanley Kubrick",cast:["Jack Nicholson","Shelley Duvall"],desc:"A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.",poster:"🏨",tags:["classic","kubrick","isolation","madness"],imdb:"https://www.imdb.com/title/tt0081505/"},
  {id:2,title:"Halloween",year:1978,country:"USA",language:"English",genre:"Slasher",rating:7.7,director:"John Carpenter",cast:["Jamie Lee Curtis","Donald Pleasence"],desc:"Fifteen years after murdering his sister, a psychopath escapes from a mental institution and returns to terrorize a small town.",poster:"🎃",tags:["slasher","classic","michael myers","holiday"],imdb:"https://www.imdb.com/title/tt0077651/"},
  {id:3,title:"The Exorcist",year:1973,country:"USA",language:"English",genre:"Supernatural",rating:8.1,director:"William Friedkin",cast:["Ellen Burstyn","Linda Blair"],desc:"When a 12-year-old girl is possessed by a mysterious entity, her mother seeks help from two priests.",poster:"👁️",tags:["possession","classic","religious","demonic"],imdb:"https://www.imdb.com/title/tt0070047/"},
  {id:4,title:"Get Out",year:2017,country:"USA",language:"English",genre:"Psychological",rating:7.7,director:"Jordan Peele",cast:["Daniel Kaluuya","Allison Williams"],desc:"A young African American man visits his white girlfriend's family estate and uncovers a disturbing secret.",poster:"🧠",tags:["social horror","modern","race","twist"],imdb:"https://www.imdb.com/title/tt5052448/"},
  {id:5,title:"A Quiet Place",year:2018,country:"USA",language:"English",genre:"Survival",rating:7.5,director:"John Krasinski",cast:["Emily Blunt","John Krasinski"],desc:"A family struggles to survive in a post-apocalyptic world inhabited by blind monsters with an acute sense of hearing.",poster:"🤫",tags:["monster","survival","silence","family"],imdb:"https://www.imdb.com/title/tt6644200/"},
  {id:6,title:"Hereditary",year:2018,country:"USA",language:"English",genre:"Supernatural",rating:7.3,director:"Ari Aster",cast:["Toni Collette","Alex Wolff"],desc:"A grieving family is haunted by their ancestry after the death of the family matriarch.",poster:"🏠",tags:["occult","ari aster","family","trauma"],imdb:"https://www.imdb.com/title/tt7784604/"},
  {id:7,title:"Midsommar",year:2019,country:"USA",language:"English",genre:"Folk Horror",rating:7.1,director:"Ari Aster",cast:["Florence Pugh","Jack Reynor"],desc:"A couple travels to Sweden for a midsummer festival that takes a disturbing turn.",poster:"🌸",tags:["folk horror","cult","daylight","ari aster"],imdb:"https://www.imdb.com/title/tt8772262/"},
  {id:8,title:"The Witch",year:2015,country:"USA",language:"English",genre:"Folk Horror",rating:6.9,director:"Robert Eggers",cast:["Anya Taylor-Joy","Ralph Ineson"],desc:"A Puritan family encounters evil forces in the New England wilderness.",poster:"🧙",tags:["puritan","witch","period horror","slow burn"],imdb:"https://www.imdb.com/title/tt4263482/"},
  {id:9,title:"It",year:2017,country:"USA",language:"English",genre:"Supernatural",rating:7.3,director:"Andy Muschietti",cast:["Bill Skarsgård","Jaeden Martell"],desc:"Seven young outcasts in Derry face their worst fears when they confront a shape-shifting monster.",poster:"🎈",tags:["clown","pennywise","kids","stephen king"],imdb:"https://www.imdb.com/title/tt1396484/"},
  {id:10,title:"Sinister",year:2012,country:"USA",language:"English",genre:"Supernatural",rating:6.8,director:"Scott Derrickson",cast:["Ethan Hawke","Juliet Rylance"],desc:"A true crime writer discovers a box of home movies that plunge his family into a nightmarish experience.",poster:"📽️",tags:["found footage","demon","writer","family"],imdb:"https://www.imdb.com/title/tt1922777/"},
  {id:11,title:"The Ring",year:2002,country:"USA",language:"English",genre:"Supernatural",rating:7.1,director:"Gore Verbinski",cast:["Naomi Watts","Martin Henderson"],desc:"A journalist investigates a mysterious videotape that seems to cause the death of anyone who views it.",poster:"📺",tags:["cursed","remake","japanese","tape"],imdb:"https://www.imdb.com/title/tt0298130/"},
  {id:12,title:"Us",year:2019,country:"USA",language:"English",genre:"Psychological",rating:6.8,director:"Jordan Peele",cast:["Lupita Nyong'o","Winston Duke"],desc:"A family's vacation turns into a nightmare when doppelgängers of themselves show up.",poster:"✂️",tags:["doppelganger","jordan peele","duality","social"],imdb:"https://www.imdb.com/title/tt6857112/"},
  // JAPAN
  {id:13,title:"Ringu",year:1998,country:"Japan",language:"Japanese",genre:"Supernatural",rating:7.2,director:"Hideo Nakata",cast:["Nanako Matsushima","Hiroyuki Sanada"],desc:"A journalist investigates a cursed videotape that kills anyone who watches it within seven days.",poster:"📼",tags:["cursed","sadako","j-horror","classic"],imdb:"https://www.imdb.com/title/tt0178868/"},
  {id:14,title:"Ju-On: The Grudge",year:2002,country:"Japan",language:"Japanese",genre:"Supernatural",rating:6.7,director:"Takashi Shimizu",cast:["Megumi Okina","Misaki Ito"],desc:"A mysterious curse spreads to all those who encounter a supernatural force lurking in a Tokyo house.",poster:"👁️",tags:["kayako","j-horror","grudge","ghost"],imdb:"https://www.imdb.com/title/tt0364384/"},
  {id:15,title:"Audition",year:1999,country:"Japan",language:"Japanese",genre:"Psychological",rating:7.2,director:"Takashi Miike",cast:["Ryo Ishibashi","Eihi Shiina"],desc:"A widower holds an audition to find a new wife, but his chosen candidate has a disturbing secret.",poster:"🪡",tags:["miike","extreme","torture","slow burn"],imdb:"https://www.imdb.com/title/tt0175143/"},
  {id:16,title:"Pulse",year:2001,country:"Japan",language:"Japanese",genre:"Supernatural",rating:6.7,director:"Kiyoshi Kurosawa",cast:["Haruhiko Kato","Kumiko Aso"],desc:"Ghosts invade the real world through the internet, spreading isolation and despair.",poster:"🖥️",tags:["internet","ghosts","loneliness","j-horror"],imdb:"https://www.imdb.com/title/tt0286751/"},
  // SOUTH KOREA
  {id:17,title:"A Tale of Two Sisters",year:2003,country:"South Korea",language:"Korean",genre:"Psychological",rating:7.2,director:"Kim Jee-woon",cast:["Im Soo-jung","Moon Geun-young"],desc:"Two sisters return home after a stint in a psychiatric institution to find their stepmother is making their lives miserable.",poster:"🌹",tags:["korean","family","twist","gothic"],imdb:"https://www.imdb.com/title/tt0365376/"},
  {id:18,title:"The Wailing",year:2016,country:"South Korea",language:"Korean",genre:"Supernatural",rating:7.4,director:"Na Hong-jin",cast:["Kwak Do-won","Hwang Jung-min"],desc:"A stranger arrives in a small village and soon locals begin losing their minds and killing their families.",poster:"🔺",tags:["korean","mystery","supernatural","village"],imdb:"https://www.imdb.com/title/tt4262980/"},
  {id:19,title:"Train to Busan",year:2016,country:"South Korea",language:"Korean",genre:"Zombie",rating:7.6,director:"Yeon Sang-ho",cast:["Gong Yoo","Jung Yu-mi"],desc:"While a zombie apocalypse breaks out in South Korea, passengers struggle to survive on a train.",poster:"🚂",tags:["zombie","action","korean","train"],imdb:"https://www.imdb.com/title/tt5700672/"},
  {id:20,title:"The Host",year:2006,country:"South Korea",language:"Korean",genre:"Monster",rating:7.0,director:"Bong Joon-ho",cast:["Song Kang-ho","Byun Hee-bong"],desc:"A monster emerges from Seoul's Han River and a family works to rescue their daughter from its clutches.",poster:"🦎",tags:["monster","bong joon-ho","family","creature"],imdb:"https://www.imdb.com/title/tt0468492/"},
  // ITALY
  {id:21,title:"Suspiria",year:1977,country:"Italy",language:"Italian",genre:"Supernatural",rating:7.4,director:"Dario Argento",cast:["Jessica Harper","Stefania Casini"],desc:"An American newcomer to a prestigious dance academy discovers the school is a front for something sinister.",poster:"🩰",tags:["giallo","argento","witches","classic"],imdb:"https://www.imdb.com/title/tt0076786/"},
  {id:22,title:"Zombie",year:1979,country:"Italy",language:"Italian",genre:"Zombie",rating:7.0,director:"Lucio Fulci",cast:["Tisa Farrow","Ian McCulloch"],desc:"Strangers search for a woman's missing father on a remote island, and encounter an army of the living dead.",poster:"🧟",tags:["zombie","fulci","gore","italian"],imdb:"https://www.imdb.com/title/tt0080057/"},
  // SPAIN
  {id:23,title:"REC",year:2007,country:"Spain",language:"Spanish",genre:"Found Footage",rating:7.4,director:"Jaume Balagueró",cast:["Manuela Velasco","Ferran Terraza"],desc:"A television reporter and cameraman follow emergency workers into a dark apartment building and are trapped inside with something terrifying.",poster:"📷",tags:["found footage","virus","quarantine","spain"],imdb:"https://www.imdb.com/title/tt1038988/"},
  {id:24,title:"The Others",year:2001,country:"Spain",language:"English",genre:"Supernatural",rating:7.6,director:"Alejandro Amenábar",cast:["Nicole Kidman","Fionnula Flanagan"],desc:"A woman who lives in a darkened old house with her photosensitive children becomes convinced her home is haunted.",poster:"🕯️",tags:["haunted house","twist","gothic","classic"],imdb:"https://www.imdb.com/title/tt0230600/"},
  // FRANCE
  {id:25,title:"Martyrs",year:2008,country:"France",language:"French",genre:"Extreme Horror",rating:7.1,director:"Pascal Laugier",cast:["Morjana Alaoui","Mylène Jampanoï"],desc:"A young woman's quest for revenge against the people who kidnapped and tormented her as a child leads her and a friend into a terrifying situation.",poster:"⛓️",tags:["extreme","french","revenge","torture"],imdb:"https://www.imdb.com/title/tt1029234/"},
  {id:26,title:"Inside",year:2007,country:"France",language:"French",genre:"Slasher",rating:6.8,director:"Alexandre Bustillo",cast:["Alysson Paradis","Béatrice Dalle"],desc:"A pregnant woman is terrorized in her home on Christmas Eve by a stranger who wants her unborn child.",poster:"🤰",tags:["french","extreme","home invasion","pregnancy"],imdb:"https://www.imdb.com/title/tt0856288/"},
  // UK
  {id:27,title:"28 Days Later",year:2002,country:"UK",language:"English",genre:"Zombie",rating:7.5,director:"Danny Boyle",cast:["Cillian Murphy","Naomie Harris"],desc:"Four weeks after a mysterious virus spreads across the UK, a handful of survivors try to find safety.",poster:"🦠",tags:["zombie","uk","virus","post-apocalyptic"],imdb:"https://www.imdb.com/title/tt0289043/"},
  {id:28,title:"The Descent",year:2005,country:"UK",language:"English",genre:"Survival",rating:7.2,director:"Neil Marshall",cast:["Shauna Macdonald","Natalie Mendoza"],desc:"A caving expedition goes horribly wrong when the group discover they are not alone in the caves.",poster:"🕳️",tags:["cave","creature","uk","survival"],imdb:"https://www.imdb.com/title/tt0435625/"},
  // AUSTRALIA
  {id:29,title:"The Babadook",year:2014,country:"Australia",language:"English",genre:"Psychological",rating:6.8,director:"Jennifer Kent",cast:["Essie Davis","Noah Wiseman"],desc:"A single mother and her child fall into a deep hole of paranoia when a mysterious children's book antagonist appears.",poster:"📖",tags:["grief","monster","mother","australian"],imdb:"https://www.imdb.com/title/tt2321549/"},
  {id:30,title:"Wolf Creek",year:2005,country:"Australia",language:"English",genre:"Slasher",rating:6.2,director:"Greg McLean",cast:["John Jarratt","Cassandra Magrath"],desc:"Stranded backpackers in remote Australia fall prey to a murderous bushman.",poster:"🔪",tags:["slasher","outback","survival","based on true events"],imdb:"https://www.imdb.com/title/tt0416508/"},
  // MEXICO
  {id:31,title:"Cronos",year:1993,country:"Mexico",language:"Spanish",genre:"Supernatural",rating:7.0,director:"Guillermo del Toro",cast:["Federico Luppi","Ron Perlman"],desc:"An antique dealer discovers a device that promises eternal life but also demands a horrifying price.",poster:"🐛",tags:["del toro","vampire","device","mexico"],imdb:"https://www.imdb.com/title/tt0104029/"},
  {id:32,title:"Tigers Are Not Afraid",year:2017,country:"Mexico",language:"Spanish",genre:"Supernatural",rating:7.1,director:"Issa López",cast:["Paola Lara","Juan Ramón López"],desc:"A dark fairy tale about a gang of five orphan children trying to survive the streets of Mexico during the drug cartel war.",poster:"🐯",tags:["fairy tale","children","cartel","supernatural"],imdb:"https://www.imdb.com/title/tt5560952/"},
  // SWEDEN
  {id:33,title:"Let the Right One In",year:2008,country:"Sweden",language:"Swedish",genre:"Supernatural",rating:8.0,director:"Tomas Alfredson",cast:["Kåre Hedebrant","Lina Leandersson"],desc:"A bullied 12-year-old boy befriends a vampire child who has lived for centuries.",poster:"🧛",tags:["vampire","sweden","romance","coming of age"],imdb:"https://www.imdb.com/title/tt1139797/"},
  // ROMANIA
  {id:34,title:"Occult",year:2012,country:"Romania",language:"Romanian",genre:"Found Footage",rating:6.2,director:"Occult",cast:["Various"],desc:"A filmmaker follows a man he believes is responsible for a mass murder in the mountains.",poster:"🎥",tags:["found footage","occult","romania","cult"],imdb:"https://www.imdb.com/title/tt2107992/"},
  // THAILAND
  {id:35,title:"Shutter",year:2004,country:"Thailand",language:"Thai",genre:"Supernatural",rating:7.1,director:"Banjong Pisanthanakun",cast:["Ananda Everingham","Natthaweeranuch Thongmee"],desc:"A young photographer and his girlfriend discover mysterious images on film after a car accident.",poster:"📸",tags:["thai","ghost","photography","guilt"],imdb:"https://www.imdb.com/title/tt0440796/"},
  {id:36,title:"4bia",year:2008,country:"Thailand",language:"Thai",genre:"Anthology",rating:6.7,director:"Various",cast:["Various"],desc:"Four horror short films set in Thailand showcasing different types of supernatural terror.",poster:"📱",tags:["anthology","thai","ghost","short films"],imdb:"https://www.imdb.com/title/tt1173786/"},
  // INDIA
  {id:37,title:"Tumbbad",year:2018,country:"India",language:"Hindi",genre:"Folk Horror",rating:8.0,director:"Rahi Anil Barve",cast:["Sohum Shah","Mohammad Samad"],desc:"A cautionary tale set in the first half of the 20th century about a man who seeks a hidden treasure connected to a deity.",poster:"🌧️",tags:["folk horror","india","greed","period"],imdb:"https://www.imdb.com/title/tt8239946/"},
  {id:38,title:"Stree",year:2018,country:"India",language:"Hindi",genre:"Comedy Horror",rating:7.6,director:"Amar Kaushik",cast:["Rajkummar Rao","Shraddha Kapoor"],desc:"A small town is terrorized by a female ghost who abducts men, based on an urban legend.",poster:"👗",tags:["comedy horror","india","urban legend","ghost"],imdb:"https://www.imdb.com/title/tt7742108/"},
  {id:39,title:"Bhool Bhulaiyaa",year:2007,country:"India",language:"Hindi",genre:"Psychological",rating:7.5,director:"Priyadarshan",cast:["Akshay Kumar","Vidya Balan"],desc:"A psychiatrist tries to solve a haunting that may be the result of a split personality.",poster:"🏚️",tags:["india","haunted","psychological","twist"],imdb:"https://www.imdb.com/title/tt0995031/"},
  // CHINA
  {id:40,title:"The Eye",year:2002,country:"China",language:"Cantonese",genre:"Supernatural",rating:6.9,director:"The Pang Brothers",cast:["Angelica Lee","Lawrence Chou"],desc:"A blind woman who receives a cornea transplant begins seeing terrifying visions.",poster:"👁️",tags:["chinese","ghost","transplant","vision"],imdb:"https://www.imdb.com/title/tt0325655/"},
  // INDONESIA
  {id:41,title:"Satan's Slaves",year:2017,country:"Indonesia",language:"Indonesian",genre:"Supernatural",rating:7.0,director:"Joko Anwar",cast:["Tara Basro","Bront Palarae"],desc:"After the death of their mother, a family is terrorized by supernatural entities.",poster:"🕷️",tags:["indonesia","ghost","family","supernatural"],imdb:"https://www.imdb.com/title/tt6192566/"},
  {id:42,title:"Pengabdi Setan",year:1982,country:"Indonesia",language:"Indonesian",genre:"Supernatural",rating:6.8,director:"Sisworo Gautama Putra",desc:"The original Indonesian horror classic about a family haunted by supernatural forces after their mother's death.",poster:"👻",tags:["indonesia","classic","ghost","family"],imdb:"https://www.imdb.com/title/tt0284784/"},
  // ARGENTINA
  {id:43,title:"Terrified",year:2017,country:"Argentina",language:"Spanish",genre:"Supernatural",rating:6.8,director:"Demián Rugna",cast:["Maxi Ghione","Norberto Gonzalo"],desc:"A team of specialists investigates a neighborhood in Buenos Aires where supernatural horrors are occurring.",poster:"🏘️",tags:["argentina","supernatural","investigators","neighborhood"],imdb:"https://www.imdb.com/title/tt7549892/"},
  // BRAZIL
  {id:44,title:"The Death of Dick Long",year:2019,country:"Brazil",language:"Portuguese",genre:"Psychological",rating:6.7,director:"Daniel Scheinert",desc:"Two friends must deal with the aftermath of a wild night that took a dark turn.",poster:"🔦",tags:["dark comedy","brazil","mystery","bizarre"],imdb:"https://www.imdb.com/title/tt8002268/"},
  // CANADA
  {id:45,title:"Pontypool",year:2008,country:"Canada",language:"English",genre:"Zombie",rating:6.7,director:"Bruce McDonald",cast:["Stephen McHattie","Lisa Houle"],desc:"A radio DJ discovers that the English language itself has become infected with a zombie virus.",poster:"📻",tags:["zombie","canada","radio","language"],imdb:"https://www.imdb.com/title/tt1226681/"},
  // GERMANY
  {id:46,title:"Goodnight Mommy",year:2014,country:"Germany/Austria",language:"German",genre:"Psychological",rating:6.8,director:"Veronika Franz",cast:["Susanne Wuest","Elias Schwarz"],desc:"Twin boys wait for their mother to return from cosmetic surgery but begin to wonder if the bandaged woman is really who she claims to be.",poster:"🩹",tags:["german","twins","identity","psychological"],imdb:"https://www.imdb.com/title/tt3316960/"},
  // RUSSIA
  {id:47,title:"Viy",year:1967,country:"Russia",language:"Russian",genre:"Supernatural",rating:7.0,director:"Konstantin Ershov",cast:["Leonid Kuravlyov","Natalya Varley"],desc:"A student must spend three nights praying over the body of a young witch who has just died.",poster:"🧿",tags:["russian","witch","folklore","classic"],imdb:"https://www.imdb.com/title/tt0062861/"},
  // NORWAY
  {id:48,title:"Troll Hunter",year:2010,country:"Norway",language:"Norwegian",genre:"Found Footage",rating:7.0,director:"André Øvredal",cast:["Otto Jespersen","Robert Storjord"],desc:"A group of students investigate a mysterious troll hunter in the Norwegian wilderness.",poster:"🧌",tags:["found footage","troll","norway","mockumentary"],imdb:"https://www.imdb.com/title/tt1740707/"},
  // DENMARK
  {id:49,title:"The Kingdom",year:1994,country:"Denmark",language:"Danish",genre:"Supernatural",rating:8.0,director:"Lars von Trier",desc:"Strange and mysterious events occur at the Kingdom hospital in Copenhagen.",poster:"🏥",tags:["danish","hospital","lars von trier","series"],imdb:"https://www.imdb.com/title/tt0108553/"},
  // IRELAND
  {id:50,title:"The Hole in the Ground",year:2019,country:"Ireland",language:"English",genre:"Supernatural",rating:5.8,director:"Lee Cronin",cast:["Seána Kerslake","James Quinn Markey"],desc:"A single mother in rural Ireland begins to suspect her son is not who he appears to be after he disappears into a mysterious sinkhole.",poster:"🕳️",tags:["ireland","child","supernatural","sinkhole"],imdb:"https://www.imdb.com/title/tt7784604/"},
  // PHILIPPINES
  {id:51,title:"Feng Shui",year:2004,country:"Philippines",language:"Filipino",genre:"Supernatural",rating:6.5,director:"Chito S. Roño",cast:["Kris Aquino","Jay Manalo"],desc:"A cursed bagua mirror brings fortune to its owner but at a terrible price.",poster:"🪞",tags:["philippines","mirror","curse","supernatural"],imdb:"https://www.imdb.com/title/tt0412852/"},
  // HONG KONG
  {id:52,title:"Rigor Mortis",year:2013,country:"Hong Kong",language:"Cantonese",genre:"Supernatural",rating:6.6,director:"Juno Mak",cast:["Chin Siu-ho","Anthony Chan"],desc:"A depressed actor moves into a rundown apartment building and discovers it is haunted.",poster:"🧟",tags:["hong kong","vampire","hopping ghost","supernatural"],imdb:"https://www.imdb.com/title/tt2515488/"},
  // TURKEY
  {id:53,title:"Baskin",year:2015,country:"Turkey",language:"Turkish",genre:"Extreme Horror",rating:6.1,director:"Can Evrenol",cast:["Gorkem Kasal","Ergun Kuyucu"],desc:"A squad of cops stumble upon a satanic ritual in an abandoned building.",poster:"🔮",tags:["turkish","satanic","extreme","police"],imdb:"https://www.imdb.com/title/tt3287644/"},
  // NEW ZEALAND
  {id:54,title:"The Frighteners",year:1996,country:"New Zealand",language:"English",genre:"Supernatural",rating:7.2,director:"Peter Jackson",cast:["Michael J. Fox","Trini Alvarado"],desc:"A man who can communicate with ghosts discovers a malevolent spirit is killing the living.",poster:"🏚️",tags:["peter jackson","ghost","comedy horror","new zealand"],imdb:"https://www.imdb.com/title/tt0116365/"},
  // FINLAND
  {id:55,title:"Lake Bodom",year:2016,country:"Finland",language:"Finnish",genre:"Slasher",rating:6.0,director:"Taneli Mustonen",cast:["Nelly Hirst-Gee","Mimosa Willamo"],desc:"Four teenagers camp at Lake Bodom, where four teens were murdered in 1960, to recreate the crime scene.",poster:"🏕️",tags:["finland","slasher","camping","based on true events"],imdb:"https://www.imdb.com/title/tt4007270/"},
  // CZECH REPUBLIC
  {id:56,title:"Valerie and Her Week of Wonders",year:1970,country:"Czech Republic",language:"Czech",genre:"Supernatural",rating:7.2,director:"Jaromil Jireš",cast:["Jaroslava Schallerová","Helena Anýžová"],desc:"A young girl experiences a dreamlike journey involving vampires, witches, and her own sexuality.",poster:"🌺",tags:["czech","surreal","vampire","fairy tale"],imdb:"https://www.imdb.com/title/tt0065638/"},
  // PORTUGAL
  {id:57,title:"The Ornithologist",year:2016,country:"Portugal",language:"Portuguese",genre:"Psychological",rating:6.2,director:"João Pedro Rodrigues",desc:"A bird watcher gets lost in the Portuguese wilderness and has a surreal, nightmarish experience.",poster:"🦅",tags:["portuguese","surreal","wilderness","psychological"],imdb:"https://www.imdb.com/title/tt4799692/"},
  // EGYPT
  {id:58,title:"Asmaa",year:2011,country:"Egypt",language:"Arabic",genre:"Psychological",rating:7.1,director:"Amr Salama",desc:"An Egyptian woman with HIV faces social stigma and prejudice in a psychological drama.",poster:"🎭",tags:["egypt","arabic","psychological","social"],imdb:"https://www.imdb.com/title/tt1836551/"},
  // ISRAEL
  {id:59,title:"Big Bad Wolves",year:2013,country:"Israel",language:"Hebrew",genre:"Psychological",rating:7.3,director:"Aharon Keshales",cast:["Lior Ashkenazi","Tzahi Grad"],desc:"A series of brutal murders puts a detective and a grieving father on a collision course with the suspected killer.",poster:"🐺",tags:["israel","revenge","thriller","dark humor"],imdb:"https://www.imdb.com/title/tt2309224/"},
  // MORE USA
  {id:60,title:"Rosemary's Baby",year:1968,country:"USA",language:"English",genre:"Supernatural",rating:8.0,director:"Roman Polanski",cast:["Mia Farrow","John Cassavetes"],desc:"A young couple moves into an apartment where the wife becomes pregnant and begins to suspect her neighbors are part of a satanic cult.",poster:"🍀",tags:["cult","satanic","pregnancy","classic"],imdb:"https://www.imdb.com/title/tt0063522/"},
  {id:61,title:"Psycho",year:1960,country:"USA",language:"English",genre:"Psychological",rating:8.5,director:"Alfred Hitchcock",cast:["Anthony Perkins","Janet Leigh"],desc:"A Phoenix secretary embezzles money and checks into a remote motel run by a troubled man and his domineering mother.",poster:"🚿",tags:["hitchcock","classic","slasher","psychological"],imdb:"https://www.imdb.com/title/tt0054215/"},
  {id:62,title:"Annihilation",year:2018,country:"USA",language:"English",genre:"Sci-Fi Horror",rating:6.8,director:"Alex Garland",cast:["Natalie Portman","Jennifer Jason Leigh"],desc:"A biologist signs up for a dangerous, secret expedition into a mysterious zone known as Area X.",poster:"🌿",tags:["sci-fi","nature","mutation","expedition"],imdb:"https://www.imdb.com/title/tt2798920/"},
  {id:63,title:"The Black Phone",year:2021,country:"USA",language:"English",genre:"Supernatural",rating:7.0,director:"Scott Derrickson",cast:["Mason Thames","Ethan Hawke"],desc:"A kidnapped 13-year-old boy discovers a disconnected phone in his captor's basement can communicate with the killer's previous victims.",poster:"📞",tags:["supernatural","kidnapping","ghost","children"],imdb:"https://www.imdb.com/title/tt7144666/"},
  {id:64,title:"Nope",year:2022,country:"USA",language:"English",genre:"Sci-Fi Horror",rating:6.8,director:"Jordan Peele",cast:["Daniel Kaluuya","Keke Palmer"],desc:"The residents of a lonely gulch in inland California have a close encounter with a mysterious entity.",poster:"🛸",tags:["ufo","jordan peele","sci-fi","western"],imdb:"https://www.imdb.com/title/tt10954984/"},
  {id:65,title:"The Conjuring",year:2013,country:"USA",language:"English",genre:"Supernatural",rating:7.5,director:"James Wan",cast:["Patrick Wilson","Vera Farmiga"],desc:"Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",poster:"🏡",tags:["based on true events","haunted","warren","supernatural"],imdb:"https://www.imdb.com/title/tt1457767/"},
  // BANGLADESH
  {id:66,title:"Aynabaji",year:2016,country:"Bangladesh",language:"Bengali",genre:"Psychological",rating:7.8,director:"Amitabh Reza Chowdhury",cast:["Chanchal Chowdhury"],desc:"A con artist in Bangladesh discovers the dark consequences of impersonating others in this psychological thriller.",poster:"🎭",tags:["bangladesh","bengali","psychological","thriller"],imdb:"https://www.imdb.com/title/tt5744960/"},
  // PAKISTAN
  {id:67,title:"Zibahkhana",year:2007,country:"Pakistan",language:"Urdu",genre:"Slasher",rating:5.5,director:"Omar Ali Khan",desc:"Pakistan's first slasher film about a group of friends who encounter a cannibalistic family in the wilderness.",poster:"🔪",tags:["pakistan","slasher","cannibal","first"],imdb:"https://www.imdb.com/title/tt0783546/"},
  // MORE JAPAN
  {id:68,title:"Ichi the Killer",year:2001,country:"Japan",language:"Japanese",genre:"Extreme Horror",rating:7.0,director:"Takashi Miike",cast:["Tadanobu Asano","Nao Omori"],desc:"A sadistic yakuza enforcer and a psychotic killer are pitted against each other in this extreme splatter film.",poster:"🩸",tags:["miike","extreme","yakuza","violence"],imdb:"https://www.imdb.com/title/tt0267697/"},
  {id:69,title:"Suicide Club",year:2001,country:"Japan",language:"Japanese",genre:"Psychological",rating:6.7,director:"Sion Sono",cast:["Ryo Ishibashi","Akaji Maro"],desc:"A wave of suicides across Japan baffles police detectives investigating the connection between the deaths.",poster:"🚉",tags:["japan","psychological","social commentary","disturbing"],imdb:"https://www.imdb.com/title/tt0340278/"},
  // MORE KOREA
  {id:70,title:"I Saw the Devil",year:2010,country:"South Korea",language:"Korean",genre:"Psychological",rating:7.8,director:"Kim Jee-woon",cast:["Lee Byung-hun","Choi Min-sik"],desc:"A secret agent exacts revenge upon a serial killer through a series of cat-and-mouse games.",poster:"😈",tags:["revenge","serial killer","korean","extreme"],imdb:"https://www.imdb.com/title/tt1588170/"},
  {id:71,title:"Parasite",year:2019,country:"South Korea",language:"Korean",genre:"Psychological",rating:8.5,director:"Bong Joon-ho",cast:["Song Kang-ho","Lee Sun-kyun"],desc:"A poor family schemes to become employed by a wealthy family, only to discover the dark reality of their employer.",poster:"🏠",tags:["oscar winner","bong joon-ho","class","dark comedy"],imdb:"https://www.imdb.com/title/tt6751668/"},
  // POLAND
  {id:72,title:"The Lure",year:2015,country:"Poland",language:"Polish",genre:"Supernatural",rating:6.7,director:"Agnieszka Smoczyńska",cast:["Marta Mazurek","Michalina Olszańska"],desc:"Two mermaid sisters emerge from the water and join a nightclub act in communist Poland, but their true nature causes problems.",poster:"🧜",tags:["mermaid","musical","poland","dark fantasy"],imdb:"https://www.imdb.com/title/tt4457572/"},
  // MORE FRANCE
  {id:73,title:"Raw",year:2016,country:"France",language:"French",genre:"Extreme Horror",rating:7.0,director:"Julia Ducournau",cast:["Garance Marillier","Ella Rumpf"],desc:"A vegetarian veterinary student discovers her taste for meat after undergoing a university hazing ritual.",poster:"🥩",tags:["cannibal","french","coming of age","body horror"],imdb:"https://www.imdb.com/title/tt4954522/"},
  {id:74,title:"High Tension",year:2003,country:"France",language:"French",genre:"Slasher",rating:6.8,director:"Alexandre Aja",cast:["Cécile De France","Maïwenn"],desc:"Best friends Marie and Alexia visit Alexia's family in the country, only for a brutal killer to interrupt their visit.",poster:"🔨",tags:["slasher","french","extreme","twist"],imdb:"https://www.imdb.com/title/tt0338130/"},
  // TAIWAN
  {id:75,title:"The Tag-Along",year:2015,country:"Taiwan",language:"Mandarin",genre:"Supernatural",rating:6.5,director:"Cheng Wei-hao",desc:"A young woman follows an old viral video of a mysterious red-dressed girl into the mountains.",poster:"👧",tags:["taiwan","ghost","girl","forest"],imdb:"https://www.imdb.com/title/tt4839948/"},
  // SINGAPORE
  {id:76,title:"Repossessed",year:2020,country:"Singapore",language:"English",genre:"Supernatural",rating:6.0,director:"Tan Seng Kiat",desc:"A Singaporean horror film about demonic possession in a modern urban setting.",poster:"👁️",tags:["singapore","possession","urban","modern"],imdb:"https://www.imdb.com/title/tt9577674/"},
  // NIGERIA
  {id:77,title:"Nneka the Pretty Serpent",year:1994,country:"Nigeria",language:"English",genre:"Supernatural",rating:6.5,director:"Andy Amenechi",desc:"A nollywood classic about a serpent deity that takes human form to exact vengeance.",poster:"🐍",tags:["nollywood","nigeria","supernatural","serpent"],imdb:"https://www.imdb.com/title/tt0110820/"},
  // MORE UK
  {id:78,title:"Midsommar",year:2019,country:"UK",language:"English",genre:"Folk Horror",rating:7.1,director:"Ari Aster",cast:["Florence Pugh"],desc:"A couple travel to Sweden to visit a rural hometown's midsummer festival.",poster:"🌼",tags:["folk","cult","sweden","relationship"],imdb:"https://www.imdb.com/title/tt8772262/"},
  {id:79,title:"The Ritual",year:2017,country:"UK",language:"English",genre:"Survival",rating:6.3,director:"David Bruckner",cast:["Rafe Spall","Arsher Ali"],desc:"A group of college friends reunite for a hiking trip in the Scandinavian wilderness.",poster:"🌲",tags:["uk","forest","monster","hiking"],imdb:"https://www.imdb.com/title/tt5638642/"},
  // CHILE
  {id:80,title:"The Club",year:2015,country:"Chile",language:"Spanish",genre:"Psychological",rating:7.0,director:"Pablo Larraín",cast:["Roberto Farias","Antonia Zegers"],desc:"A group of disgraced priests live in seclusion under the watch of a nun, until a stranger arrives.",poster:"⛪",tags:["chile","priest","psychological","dark"],imdb:"https://www.imdb.com/title/tt4048272/"},
];
